## Copyright 2015 StreamBright LLC
#
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
#
##     http://www.apache.org/licenses/LICENSE-2.0
#
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
---

- name: Removing files not needed
  file: path=/etc/security/limits.d state=absent
  sudo: yes

- name: Setting up limits.conf
  template: src=limits.conf.j2 dest=/etc/security/limits.conf owner=root group=root mode=0644
  sudo: yes

- name: Disabling ipv6
  sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present sysctl_set=yes reload=yes
  sudo: yes

- name: Configuring swappiness
  sysctl: name=vm.swappiness value=5 state=present
  sudo: yes

- name: Configuring kernel panic
  sysctl: name=kernel.panic state=absent
  sudo: yes

- name: Configuring rmem_max
  sysctl: name=net.core.rmem_max value=16777216 state=present
  sudo: yes

- name: Configuring wmem_max
  sysctl: name=net.core.wmem_max=16777216 state=present
  sudo: yes

- name: Configuring tcp_rmem
  sysctl: name=net.ipv4.tcp_rmem value='4096 87380 16777216' state=present
  sudo: yes

- name: Configuring tcp_wmem
  sysctl: name=net.ipv4.tcp_wmem value='4096 87380 16777216' state=present
  sudo: yes

- name: Configuring tcp_tw_reuse
  sysctl: name=net.ipv4.tcp_tw_reuse value=1 state=present
  sudo: yes

- name: Configuring tcp_tw_recycle
  sysctl: name=net.ipv4.tcp_tw_recycle value=1 state=present
  sudo: yes

- name: Configuring tcp_fin_timeout
  sysctl: name=net.ipv4.tcp_fin_timeout value=30 state=present
  sudo: yes

- name: Configuring ipv4.tcp_syncookies
  sysctl: name=net.ipv4.tcp_syncookies value=1 state=present
  sudo: yes

- name: Configuring tcp_max_syn_backlog
  sysctl: name=net.ipv4.tcp_max_syn_backlog value=65536 state=present
  sudo: yes

- name: Ensure the firewall is disabled
  service: name=firewalld state=stopped enabled=no
  sudo: yes


