## Copyright 2015 StreamBright LLC
#
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
#
##     http://www.apache.org/licenses/LICENSE-2.0
#
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
---
- name: Installing epel-release
  yum: state=present name=epel-release
  sudo: yes

- name: Installing packages
  yum: state=present name={{ item }}
  with_items: "{{ packages }}"
  sudo: yes

- name: Creating locate database
  command: updatedb
  changed_when: false
  sudo: yes
